# This is a basic workflow to help you get started with Actions

name: MyFirstWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push for all branches
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "MyFirstJob"
  MyFirstJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, JTOH!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: npm install
        run: npm install -g bats
        
      - name: check bats version
        run: bats -v
